package nl.fontys.indbe.s3cb13_io_room_usage_detection_backend.business;

import nl.fontys.indbe.s3cb13_io_room_usage_detection_backend.business.message.CreateCameraConnectionRequest;
import nl.fontys.indbe.s3cb13_io_room_usage_detection_backend.business.message.CreateCameraConnectionResponse;

public interface UpdateCameraConnectionUseCase {
    CreateCameraConnectionResponse updateCameraConnection(CreateCameraConnectionRequest request);
}
